# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'UIForm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIForm
  pod 'IQKeyboardManager'
  pod 'UIFloatLabelTextView'
  pod 'UIFloatLabelTextField'

  target 'UIFormTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
